COHEREAPIKEY = "fIoAGwQeTy8HjNgIlhiHrBf9CS0Zu30svaxDTSjM"

EDENAPIKEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZThhMTkyOWYtYjdkZi00NTU2LTgwOWItODZmZGQwY2RhMDBmIiwidHlwZSI6ImFwaV90b2tlbiJ9.-8rjapE7HaIi7jLyGST1rAHvakbEdAT-Of7lSSBq1R8"